# Generated by Django 3.0.3 on 2020-03-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='price',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='status',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='product_images')),
                ('description', models.TextField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Published', 'PUBLISHED'), ('Stock Out', 'STOCK OUT')], default='PENDING', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-id'],
            },
        ),
    ]
