# Generated by Django 3.0.3 on 2020-03-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_querystrings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='querystrings',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='querystrings',
            name='report',
            field=models.TextField(default='none', max_length=500),
            preserve_default=False,
        ),
    ]
